=== happy0wnage/TransportApp/src/main/resources/security/rules.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="security">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rule" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="role">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="user"/>
                    <xs:enumeration value="common"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="urls">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="url" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== happy0wnage/TransportApp/src/main/resources/security/rules.xml
<?xml version="1.0" encoding="UTF-8" ?>
<security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="rules.xsd">
    <rule>
        <role>user</role>
        <urls>
			<url>/index.html</url>
            <url>/simulation/view</url>
            <url>/login</url>
            <url>/user/register</url>
            <url>/user/add</url>
			
            <url>/arc/add</url>
            <url>/arc/delete</url>
            <url>/arc/update</url>

            <url>/bus/add</url>
            <url>/bus/delete</url>
            <url>/bus/update</url>

            <url>/route/add</url>
            <url>/route/delete</url>
            <url>/route/update</url>

            <url>/station/add</url>
            <url>/station/delete</url>
            <url>/station/update</url>

            <url>/simulation/start</url>
            <url>/simulation/pause</url>
            <url>/simulation/addBus</url>

            <url>/logout</url>
            <url>/download/results</url>
        </urls>
    </rule>

    <rule>
        <role>common</role>
        <urls>
            <url>/index.html</url>
            <url>/simulation/view</url>
            <url>/login</url>
            <url>/user/register</url>
            <url>/user/add</url>
			<url>/download/results</url>
        </urls>
    </rule>


</security>
